In [1]:
import pandas as pd
df= pd.read_csv("flipkart_com-ecommerce_sample.csv")
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,No rating available,No rating available,WallDesign,"{""product_specification""=>[{""key""=>""Number of ..."
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,Buy Wallmantra Large Vinyl Stickers Sticker fo...,No rating available,No rating available,Wallmantra,"{""product_specification""=>[{""key""=>""Number of ..."
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."

In [62]:
import numpy as np
import re
import random
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
 
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
print("All imports successful")

All imports successful

In [3]:
print("Shape:", df.shape)

Shape: (20000, 15)

In [4]:
df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='object')

In [5]:
df.dtypes

uniq_id                     object
crawl_timestamp             object
product_url                 object
product_name                object
product_category_tree       object
pid                         object
retail_price               float64
discounted_price           float64
image                       object
is_FK_Advantage_product       bool
description                 object
product_rating              object
overall_rating              object
brand                       object
product_specifications      object
dtype: object

In [6]:
df.head(3)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.00,379.00,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.00,22646.00,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.00,499.00,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: bool(1), float64(2), object(12)
memory usage: 2.2+ MB

In [8]:
df.describe(include='all')

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
count,20000,20000,20000,20000,20000,20000,19922.00,19922.00,19997,20000,19998,20000,20000,14136,19986
unique,20000,371,20000,12676,6466,19998,NaN,NaN,18589,2,17539,36,36,3499,18825
top,c5692a03af64973a9e17fc95ac22e2c2,2015-12-01 12:40:44 +0000,http://www.flipkart.com/999store-medium-paper-...,TheLostPuppy Back Cover for Apple iPad Air,"[""Jewellery >> Necklaces & Chains >> Necklaces""]",JEAEGE8Q8GXYFTGU,NaN,NaN,"[""http://img6a.flixcart.com/image/car-mat/m/t/...",False,TheLostPuppy Back Cover for Apple iPad Air (Mu...,No rating available,No rating available,Allure Auto,"{""product_specification""=>[{""key""=>""Type"", ""va..."
freq,1,1979,1,134,1567,2,NaN,NaN,45,19215,92,18151,18151,469,71
mean,NaN,NaN,NaN,NaN,NaN,NaN,2979.21,1973.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9009.64,7333.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,35.00,35.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,666.00,350.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1040.00,550.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1999.00,999.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,571230.00,571230.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().sum

<bound method DataFrame.sum of        uniq_id  crawl_timestamp  product_url  product_name  \
0        False            False        False         False
1        False            False        False         False
2        False            False        False         False
3        False            False        False         False
4        False            False        False         False
...        ...              ...          ...           ...
19995    False            False        False         False
19996    False            False        False         False
19997    False            False        False         False
19998    False            False        False         False
19999    False            False        False         False

       product_category_tree    pid  retail_price  discounted_price  image  \
0                      False  False         False             False  False
1                      False  False         False             False  False
2                      False  False         False             False  False
3                      False  False         False             False  False
4                      False  False         False             False  False
...                      ...    ...           ...               ...    ...
19995                  False  False         False             False  False
19996                  False  False         False             False  False
19997                  False  False         False             False  False
19998                  False  False         False             False  False
19999                  False  False         False             False  False

       is_FK_Advantage_product  description  product_rating  overall_rating  \
0                        False        False           False           False
1                        False        False           False           False
2                        False        False           False           False
3                        False        False           False           False
4                        False        False           False           False
...                        ...          ...             ...             ...
19995                    False        False           False           False
19996                    False        False           False           False
19997                    False        False           False           False
19998                    False        False           False           False
19999                    False        False           False           False

       brand  product_specifications
0      False                   False
1      False                   False
2      False                   False
3      False                   False
4      False                   False
...      ...                     ...
19995  False                   False
19996  False                   False
19997  False                   False
19998  False                   False
19999  False                   False

[20000 rows x 15 columns]>

In [23]:
print("\n=== NULL PERCENTAGES ===")
null_pct = (df.isnull().sum() / len(df) * 100).round(2)
print(null_pct[null_pct > 0])

=== NULL PERCENTAGES ===
retail_price              0.39
discounted_price          0.39
image                     0.02
description               0.01
brand                    29.32
product_specifications    0.07
dtype: float64

In [25]:
print(f"\n=== DUPLICATES === {df.duplicated().sum()} duplicate rows")

=== DUPLICATES === 0 duplicate rows

In [31]:
df.drop(['product_url','image','is_FK_Advantage_product','product_specifications','crawl_timestamp','pid','description','product_rating','overall_rating'] , axis=1, errors='ignore' , inplace=True)

In [32]:
df

,uniq_id,product_name,product_category_tree,retail_price,discounted_price,brand,main_category,sub_category,discount_amount,discount_pct,discount_band,product_id
0,c2d766ca982eca8304150849735ffef9,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.00,379.00,Alisha,Clothing,Women's Clothing,620.00,62.06,60%+,P00001
1,7f7036a6d550aaa89d34c77bd39a5e48,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.00,22646.00,Fabhomedecor,Furniture,Living Room Furniture,9511.00,29.58,20-30%,P00002
2,f449ec65dcbc041b6ae5e6a32717d01b,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",999.00,499.00,Aw,Footwear,Women's Footwear,500.00,50.05,50-60%,P00003
3,0973b37acd0c664e3de26e97e5571454,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",699.00,267.00,Alisha,Clothing,Women's Clothing,432.00,61.80,60%+,P00004
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",220.00,210.00,Sicons,Pet Supplies,Grooming,10.00,4.55,0-10%,P00005
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",1500.00,730.00,Walldesign,Baby Care,Baby & Kids Gifts,770.00,51.33,50-60%,P19918
19996,71ac419198359d37b8fe5e3fffdfee09,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",1429.00,1143.00,Wallmantra,Baby Care,Baby & Kids Gifts,286.00,20.01,20-30%,P19919
19997,93e9d343837400ce0d7980874ece471c,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",1299.00,999.00,Elite Collection,Baby Care,Baby & Kids Gifts,300.00,23.09,20-30%,P19920
19998,669e79b8fa5d9ae020841c0c97d5e935,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",1499.00,1199.00,Elite Collection,Baby Care,Baby & Kids Gifts,300.00,20.01,20-30%,P19921
19999,cb4fa87a874f715fff567f7b7b3be79c,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",1499.00,999.00,Elite Collection,Baby Care,Baby & Kids Gifts,500.00,33.36,30-40%,P19922

In [33]:
# Clean retail_price
#  Raw format: "₹2,999" or "2999.0" or NaN
# ─────────────────────────────────────────────────────────────
def clean_price(val):
    if pd.isnull(val):
        return np.nan
    val = str(val)
    val = re.sub(r'[₹,\s]', '', val)   # remove ₹ symbol, commas, spaces
    val = re.sub(r'[^\d.]', '', val)    # keep only digits and decimal point
    try:
        return float(val)
    except:
        return np.nan
 
df['retail_price'] = df['retail_price'].apply(clean_price)
df['discounted_price'] = df['discounted_price'].apply(clean_price)

In [34]:

print("retail_price sample:")
print(df['retail_price'].describe())
print("\ndiscounted_price sample:")
print(df['discounted_price'].describe())

retail_price sample:
count    19922.00
mean      2979.21
std       9009.64
min         35.00
25%        666.00
50%       1040.00
75%       1999.00
max     571230.00
Name: retail_price, dtype: float64

discounted_price sample:
count    19922.00
mean      1973.40
std       7333.59
min         35.00
25%        350.00
50%        550.00
75%        999.00
max     571230.00
Name: discounted_price, dtype: float64

In [35]:
#  CELL 7 — Extract main_category from product_category_tree
#  Raw format: "Electronics >> Mobiles >> Samsung Mobiles"
# ─────────────────────────────────────────────────────────────
def extract_main_category(val):
    if pd.isnull(val):
        return 'Unknown'
    val = str(val)
    # Remove brackets and quotes that Kaggle dataset wraps around this field
    val = val.strip('[]"\'')
    # Split on >> and take the first part
    parts = val.split('>>')
    return parts[0].strip() if parts else 'Unknown'
 
def extract_sub_category(val):
    if pd.isnull(val):
        return 'Unknown'
    val = str(val).strip('[]"\'')
    parts = val.split('>>')
    return parts[1].strip() if len(parts) > 1 else 'Unknown'
 
df['main_category'] = df['product_category_tree'].apply(extract_main_category)
df['sub_category']  = df['product_category_tree'].apply(extract_sub_category)
 
print("Top 15 main categories:")
print(df['main_category'].value_counts().head(15))

Top 15 main categories:
main_category
Clothing                      6171
Jewellery                     3522
Footwear                      1225
Mobiles & Accessories         1097
Automotive                    1010
Home Decor & Festive Needs     927
Beauty and Personal Care       709
Home Furnishing                700
Kitchen & Dining               645
Computers                      573
Watches                        528
Baby Care                      481
Tools & Hardware               387
Toys & School Supplies         329
Pens & Stationery              313
Name: count, dtype: int64

In [36]:
#  CELL 8 — Clean brand column
# ─────────────────────────────────────────────────────────────
df['brand'] = df['brand'].astype(str).str.strip().str.title()
df['brand'] = df['brand'].replace({'Nan': 'Unknown', 'None': 'Unknown', '': 'Unknown'})
 
print("Top 20 brands:")
print(df['brand'].value_counts().head(20))

Top 20 brands:
brand
Unknown         5851
Allure Auto      468
Regular          309
Voylla           299
Slim             284
Thelostpuppy     250
Karatcraft       211
Black            167
White            155
Dailyobjects     144
Speedwav         141
Radiant Bay      132
Red              109
Enthopia         101
Pink             100
Bluestone         99
Homeehub          95
Purple            85
Wallmantra        83
Jewelizer         78
Name: count, dtype: int64

In [37]:
#  CELL 9 — Drop rows with critical nulls
#  We need at least a price and category to do analysis
# ─────────────────────────────────────────────────────────────
print(f"Before drop: {df.shape[0]} rows")
 
df = df.dropna(subset=['retail_price', 'discounted_price'])
df = df[df['retail_price'] > 0]
df = df[df['discounted_price'] > 0]
 
# Remove impossible prices (discounted > retail means bad data)
df = df[df['discounted_price'] <= df['retail_price']]
 
print(f"After drop:  {df.shape[0]} rows")
print(f"Removed:     {df.shape[0]} rows with bad price data")

Before drop: 19922 rows
After drop:  19922 rows
Removed:     19922 rows with bad price data

In [38]:
df['product_id'] = ['P' + str(i+1).zfill(5) for i in range(len(df))]
# P00001, P00002, P00003 ... clean and readable

In [45]:
df

,product_name,retail_price,discounted_price,brand,main_category,discount_pct,product_id
0,Alisha Solid Women's Cycling Shorts,999.00,379.00,Alisha,Clothing,62.06,P00001
1,FabHomeDecor Fabric Double Sofa Bed,32157.00,22646.00,Fabhomedecor,Furniture,29.58,P00002
2,AW Bellies,999.00,499.00,Aw,Footwear,50.05,P00003
3,Alisha Solid Women's Cycling Shorts,699.00,267.00,Alisha,Clothing,61.80,P00004
4,Sicons All Purpose Arnica Dog Shampoo,220.00,210.00,Sicons,Pet Supplies,4.55,P00005
...,...,...,...,...,...,...,...
19995,WallDesign Small Vinyl Sticker,1500.00,730.00,Walldesign,Baby Care,51.33,P19918
19996,Wallmantra Large Vinyl Stickers Sticker,1429.00,1143.00,Wallmantra,Baby Care,20.01,P19919
19997,Elite Collection Medium Acrylic Sticker,1299.00,999.00,Elite Collection,Baby Care,23.09,P19920
19998,Elite Collection Medium Acrylic Sticker,1499.00,1199.00,Elite Collection,Baby Care,20.01,P19921
19999,Elite Collection Medium Acrylic Sticker,1499.00,999.00,Elite Collection,Baby Care,33.36,P19922

In [46]:
df.drop(['uniq_id','product_category_tree','sub_category','discount_amount','discount_band'], axis=1, errors='ignore' , inplace=True)

In [48]:
df

,product_name,retail_price,discounted_price,brand,main_category,discount_pct,product_id
0,Alisha Solid Women's Cycling Shorts,999.00,379.00,Alisha,Clothing,62.06,P00001
1,FabHomeDecor Fabric Double Sofa Bed,32157.00,22646.00,Fabhomedecor,Furniture,29.58,P00002
2,AW Bellies,999.00,499.00,Aw,Footwear,50.05,P00003
3,Alisha Solid Women's Cycling Shorts,699.00,267.00,Alisha,Clothing,61.80,P00004
4,Sicons All Purpose Arnica Dog Shampoo,220.00,210.00,Sicons,Pet Supplies,4.55,P00005
...,...,...,...,...,...,...,...
19995,WallDesign Small Vinyl Sticker,1500.00,730.00,Walldesign,Baby Care,51.33,P19918
19996,Wallmantra Large Vinyl Stickers Sticker,1429.00,1143.00,Wallmantra,Baby Care,20.01,P19919
19997,Elite Collection Medium Acrylic Sticker,1299.00,999.00,Elite Collection,Baby Care,23.09,P19920
19998,Elite Collection Medium Acrylic Sticker,1499.00,1199.00,Elite Collection,Baby Care,20.01,P19921
19999,Elite Collection Medium Acrylic Sticker,1499.00,999.00,Elite Collection,Baby Care,33.36,P19922

In [19]:
#Feature Engineering
# 1. Discount amount and percentage
df['discount_amount'] = df['retail_price'] - df['discounted_price']
df['discount_pct'] = ((df['discount_amount'] / df['retail_price']) * 100).round(2)

In [22]:
print("=== FINAL DATASET SUMMARY ===")
print(f"Total products:        {len(df):,}")
print(f"Categories:            {df['main_category'].nunique()}")
print(f"Brands:                {df['brand'].nunique()}")
print(f"Avg discount:          {df['discount_pct'].mean():.1f}%")
print(f"Avg price (MRP):       ₹{df['retail_price'].mean():,.0f}")
print(f"Avg selling price:     ₹{df['discounted_price'].mean():,.0f}")

=== FINAL DATASET SUMMARY ===
Total products:        19,922
Categories:            262
Brands:                3357
Avg discount:          40.5%
Avg price (MRP):       ₹2,979
Avg selling price:     ₹1,973

In [51]:
df.columns

Index(['product_name', 'retail_price', 'discounted_price', 'brand',
       'main_category', 'discount_pct', 'product_id'],
      dtype='object')

In [53]:
dim_products = df[[
    'product_id',
    'product_name',
    'main_category',
    'brand',
    'retail_price',
    'discounted_price',
]].copy()

dim_products['discount_pct'] = (
    (dim_products['retail_price'] - dim_products['discounted_price'])
    / dim_products['retail_price'] * 100
).round(2)

# ── Verify ────────────────────────────────────────────────
print(f"Total products:  {len(dim_products):,}")
print(f"ID format check: {dim_products['product_id'].head(3).tolist()}")
print(f"Categories:      {dim_products['main_category'].nunique()}")
print(f"Nulls:           {dim_products.isnull().sum().sum()}")
print(dim_products.head(3))

Total products:  19,922
ID format check: ['P00001', 'P00002', 'P00003']
Categories:      262
Nulls:           0
  product_id                         product_name main_category         brand  \
0     P00001  Alisha Solid Women's Cycling Shorts      Clothing        Alisha
1     P00002  FabHomeDecor Fabric Double Sofa Bed     Furniture  Fabhomedecor
2     P00003                           AW Bellies      Footwear            Aw

   retail_price  discounted_price  discount_pct
0        999.00            379.00         62.06
1      32157.00          22646.00         29.58
2        999.00            499.00         50.05

In [54]:
dim_products.to_csv('dim_products.csv', index=False)
print("\nSaved: dim_products.csv")

Saved: dim_products.csv

In [59]:
#  STEP 2 — Generate dim_customers (10,000 Indian customers)
# ─────────────────────────────────────────────────────────────
 
# Real Indian cities with realistic population weighting
CITIES = {
    'Mumbai':       ('Maharashtra', 0.12),
    'Delhi':        ('Delhi',       0.11),
    'Bengaluru':    ('Karnataka',   0.10),
    'Hyderabad':    ('Telangana',   0.08),
    'Chennai':      ('Tamil Nadu',  0.07),
    'Kolkata':      ('West Bengal', 0.07),
    'Pune':         ('Maharashtra', 0.06),
    'Ahmedabad':    ('Gujarat',     0.05),
    'Jaipur':       ('Rajasthan',   0.04),
    'Lucknow':      ('UP',          0.04),
    'Bhopal':       ('MP',          0.03),
    'Indore':       ('MP',          0.03),
    'Surat':        ('Gujarat',     0.03),
    'Nagpur':       ('Maharashtra', 0.03),
    'Patna':        ('Bihar',       0.02),
    'Coimbatore':   ('Tamil Nadu',  0.02),
    'Bhubaneswar':  ('Odisha',      0.02),
    'Kochi':        ('Kerala',      0.02),
    'Chandigarh':   ('Punjab',      0.02),
    'Guwahati':     ('Assam',       0.02),
}
 
city_names   = list(CITIES.keys())
city_weights = [CITIES[c][1] for c in city_names]
 
# Indian first + last names for realism
FIRST_NAMES = [
    'Aarav','Vivaan','Aditya','Vihaan','Arjun','Sai','Reyansh',
    'Ayaan','Krishna','Ishaan','Ananya','Diya','Priya','Sneha',
    'Pooja','Neha','Kavya','Riya','Meera','Sakshi','Rahul',
    'Rohit','Amit','Vikram','Suresh','Ramesh','Deepak','Raj',
    'Nikhil','Kunal','Shruti','Divya','Swati','Rekha','Sunita'
]
LAST_NAMES = [
    'Sharma','Verma','Singh','Patel','Kumar','Gupta','Joshi',
    'Mishra','Yadav','Tiwari','Nair','Iyer','Reddy','Rao',
    'Mehta','Shah','Jain','Agarwal','Bose','Chatterjee',
    'Pillai','Menon','Desai','Patil','Shukla','Pandey'
]
 
N_CUSTOMERS = 10000
customer_ids = ['C' + str(i+1).zfill(6) for i in range(N_CUSTOMERS)]
cities_chosen = random.choices(city_names, weights=city_weights, k=N_CUSTOMERS)
 
dim_customers = pd.DataFrame({
    'customer_id':   customer_ids,
    'customer_name': [
        random.choice(FIRST_NAMES) + ' ' + random.choice(LAST_NAMES)
        for _ in range(N_CUSTOMERS)
    ],
    'city':  cities_chosen,
    'state': [CITIES[c][0] for c in cities_chosen],
    'age':   np.random.choice(
        range(18, 65),
        size=N_CUSTOMERS,
        p=np.array([
            0.03 if a < 22 else
            0.04 if a < 30 else
            0.035 if a < 40 else
            0.02 if a < 50 else
            0.01
            for a in range(18, 65)
        ]) / sum([
            0.03 if a < 22 else
            0.04 if a < 30 else
            0.035 if a < 40 else
            0.02 if a < 50 else
            0.01
            for a in range(18, 65)
        ])
    ),
    'customer_segment': np.random.choice(
        ['Budget Shopper','Regular','Premium','Loyal'],
        size=N_CUSTOMERS,
        p=[0.35, 0.40, 0.15, 0.10]
    )
})
 
print(f"Customers generated: {len(dim_customers):,}")

Customers generated: 10,000

In [60]:
#  STEP 3 — Generate dim_sellers (500 sellers)
# ─────────────────────────────────────────────────────────────
 
SELLER_NAMES = [
    'TechMart India','QuickShop','RetailKing','BestBuy India',
    'MegaStore','ShopEasy','ValueMart','PrimeSeller','TopDeals',
    'FlashSale India','TrustSeller','ReliableMart','IndiaShop',
    'DealZone','SmartBuy','BargainHub','QualityFirst','FastShip',
    'MumbaiMart','DelhiDeals','BengaluruBuy','HydStore','ChennaiShop'
]
 
N_SELLERS = 500
dim_sellers = pd.DataFrame({
    'seller_id':     ['S' + str(i+1).zfill(4) for i in range(N_SELLERS)],
    'seller_name':   [
        random.choice(SELLER_NAMES) + ' ' + str(random.randint(1,999))
        for _ in range(N_SELLERS)
    ],
    'seller_city':   random.choices(city_names, weights=city_weights, k=N_SELLERS),
    'seller_rating': np.round(np.random.normal(4.1, 0.5, N_SELLERS).clip(1, 5), 1),
    'joined_year':   np.random.choice(range(2015, 2024), size=N_SELLERS,
                        p=[0.05,0.08,0.10,0.12,0.15,0.15,0.15,0.12,0.08])
})
 
print(f"Sellers generated:   {len(dim_sellers):,}")

Sellers generated:   500

In [63]:
#  STEP 4 — Generate fact_orders (100,000 orders over 2 years)
#
#  Key realism features:
#  - Big Billion Days spike (Oct): 3x normal volume
#  - Diwali spike (Oct-Nov): 2x normal
#  - Weekend boost: 1.3x
#  - Category-based pricing logic
#  - Customer segment affects purchase behavior
# ─────────────────────────────────────────────────────────────
 
START_DATE = datetime(2022, 1, 1)
END_DATE   = datetime(2023, 12, 31)
N_ORDERS   = 100000
 
# Date generation with festive season weighting
def generate_order_dates(n):
    dates = []
    current = START_DATE
    date_pool = []
    weights_pool = []
 
    while current <= END_DATE:
        month = current.month
        # Base weight
        weight = 1.0
        # Festive season boost
        if month == 10:  weight = 3.5   # Big Billion Days
        elif month == 11: weight = 2.5  # Post-Diwali
        elif month == 12: weight = 1.8  # Christmas/New Year
        elif month == 1:  weight = 1.5  # Republic Day sale
        elif month in [4,5]: weight = 1.3  # Summer sale
        # Weekend boost
        if current.weekday() >= 5: weight *= 1.3
        date_pool.append(current)
        weights_pool.append(weight)
        current += timedelta(days=1)
 
    chosen = random.choices(date_pool, weights=weights_pool, k=n)
    return chosen
 
print("Generating order dates with festive season patterns...")
order_dates = generate_order_dates(N_ORDERS)
 
# Sample products weighted by category popularity
category_weights_map = {
    'Clothing':         0.20,
    'Electronics':      0.18,
    'Footwear':         0.10,
    'Furniture':        0.08,
    'Jewellery':        0.07,
    'Home Furnishing':  0.07,
    'Kitchen':          0.06,
    'Sports':           0.05,
    'Toys & School':    0.04,
    'Beauty':           0.04,
    'Mobiles':          0.04,
    'Other':            0.07,
}
 
# Assign product weights based on category
dim_products['pop_weight'] = dim_products['main_category'].map(
    lambda c: next(
        (v for k,v in category_weights_map.items() if k.lower() in c.lower()),
        0.03
    )
)
product_probs = dim_products['pop_weight'] / dim_products['pop_weight'].sum()
 
print("Sampling products for orders...")
sampled_products = dim_products.sample(
    n=N_ORDERS, replace=True, weights=product_probs
).reset_index(drop=True)
 
# Generate quantities (most orders = 1 item)
quantities = np.random.choice([1,2,3,4,5], size=N_ORDERS, p=[0.70,0.17,0.07,0.04,0.02])
 
# Payment methods — UPI dominates in India
payment_methods = np.random.choice(
    ['UPI','Credit Card','Debit Card','Net Banking','COD','EMI'],
    size=N_ORDERS,
    p=[0.38, 0.18, 0.15, 0.10, 0.12, 0.07]
)
 
# Order status — most delivered, some cancelled/returned
order_statuses = np.random.choice(
    ['Delivered','Delivered','Delivered','Delivered',
     'Cancelled','Returned','Processing'],
    size=N_ORDERS
)
 
# Build fact_orders
fact_orders = pd.DataFrame({
    'order_id':       ['ORD' + str(i+1).zfill(7) for i in range(N_ORDERS)],
    'order_date':     [d.strftime('%Y-%m-%d') for d in order_dates],
    'order_month':    [d.month for d in order_dates],
    'order_year':     [d.year for d in order_dates],
    'order_quarter':  [f"Q{(d.month-1)//3+1}" for d in order_dates],
    'is_weekend':     [1 if d.weekday() >= 5 else 0 for d in order_dates],
 
    # Big Billion Days = Oct 1-7
    'is_big_billion_day': [
        1 if (d.month == 10 and d.day <= 7) else 0 for d in order_dates
    ],
    # Festive season = Oct + Nov
    'is_festive_season': [
        1 if d.month in [10, 11] else 0 for d in order_dates
    ],
 
    'customer_id':    random.choices(dim_customers['customer_id'].tolist(), k=N_ORDERS),
    'product_id':     sampled_products['product_id'].tolist(),
    'seller_id':      random.choices(dim_sellers['seller_id'].tolist(), k=N_ORDERS),
 
    'quantity':       quantities,
    'unit_price':     sampled_products['discounted_price'].round(2).tolist(),
    'retail_price':   sampled_products['retail_price'].round(2).tolist(),
    'total_amount':   (sampled_products['discounted_price'] * quantities).round(2).tolist(),
    'discount_pct':   sampled_products['discount_pct'].round(2).tolist(),
 
    'payment_method': payment_methods,
    'order_status':   order_statuses,
 
    'main_category':  sampled_products['main_category'].tolist(),
})
 
print(f"Orders generated:    {len(fact_orders):,}")
print(f"  Big Billion Days orders: {fact_orders['is_big_billion_day'].sum():,}")
print(f"  Festive season orders:   {fact_orders['is_festive_season'].sum():,}")
print(f"  Returned orders:         {(fact_orders['order_status']=='Returned').sum():,}")

Generating order dates with festive season patterns...
Sampling products for orders...
Orders generated:    100,000
  Big Billion Days orders: 4,410
  Festive season orders:   33,562
  Returned orders:         14,181

In [64]:
#  STEP 5 — Generate fact_returns
#  Only for orders with status = 'Returned'
# ─────────────────────────────────────────────────────────────
 
returned_orders = fact_orders[fact_orders['order_status'] == 'Returned'].copy()
 
RETURN_REASONS = {
    'Clothing':    ['Size issue','Wrong item delivered','Quality not as expected','Changed mind'],
    'Electronics': ['Defective product','Not as described','Better price elsewhere','Damaged in transit'],
    'Footwear':    ['Size issue','Quality issue','Wrong item','Damaged'],
    'Furniture':   ['Damaged in transit','Wrong item','Assembly issue','Quality issue'],
    'default':     ['Quality not as expected','Wrong item','Changed mind',
                    'Defective product','Better price elsewhere','Damaged in transit']
}
 
def get_return_reason(category):
    reasons = RETURN_REASONS.get(category, RETURN_REASONS['default'])
    return random.choice(reasons)
 
return_dates = [
    datetime.strptime(d, '%Y-%m-%d') + timedelta(days=random.randint(1, 10))
    for d in returned_orders['order_date']
]
 
fact_returns = pd.DataFrame({
    'return_id':     ['RET' + str(i+1).zfill(6) for i in range(len(returned_orders))],
    'order_id':      returned_orders['order_id'].values,
    'product_id':    returned_orders['product_id'].values,
    'customer_id':   returned_orders['customer_id'].values,
    'main_category': returned_orders['main_category'].values,
    'return_date':   [d.strftime('%Y-%m-%d') for d in return_dates],
    'return_reason': [
        get_return_reason(cat) for cat in returned_orders['main_category'].values
    ],
    'refund_amount': returned_orders['total_amount'].values,
    'return_status': np.random.choice(
        ['Refunded','Replacement Sent','Processing'],
        size=len(returned_orders),
        p=[0.65, 0.25, 0.10]
    )
})
 
print(f"Returns generated:   {len(fact_returns):,}")

Returns generated:   14,181

In [65]:
#  STEP 6 — Final data quality check
# ─────────────────────────────────────────────────────────────
print("\n" + "="*55)
print(" FINAL DATASET SUMMARY")
print("="*55)
print(f"dim_products:   {len(dim_products):,} rows  (real Kaggle data)")
print(f"dim_customers:  {len(dim_customers):,} rows  (synthetic Indian customers)")
print(f"dim_sellers:    {len(dim_sellers):,} rows  (synthetic sellers)")
print(f"fact_orders:    {len(fact_orders):,} rows  (2 years of orders)")
print(f"fact_returns:   {len(fact_returns):,} rows  (returned orders)")
 
print("\nOrder status breakdown:")
print(fact_orders['order_status'].value_counts())
 
print("\nTop 5 categories by order volume:")
print(fact_orders['main_category'].value_counts().head())
 
print("\nPayment method split:")
print(fact_orders['payment_method'].value_counts())
 
print("\nBig Billion Days vs Regular Day avg orders:")
bbd     = fact_orders[fact_orders['is_big_billion_day']==1]['order_date'].value_counts().mean()
regular = fact_orders[fact_orders['is_big_billion_day']==0]['order_date'].value_counts().mean()
print(f"  Big Billion Days: {bbd:.0f} orders/day")
print(f"  Regular days:     {regular:.0f} orders/day")
print(f"  Spike multiplier: {bbd/regular:.1f}x")

=======================================================
 FINAL DATASET SUMMARY
=======================================================
dim_products:   19,922 rows  (real Kaggle data)
dim_customers:  10,000 rows  (synthetic Indian customers)
dim_sellers:    500 rows  (synthetic sellers)
fact_orders:    100,000 rows  (2 years of orders)
fact_returns:   14,181 rows  (returned orders)

Order status breakdown:
order_status
Delivered     57205
Cancelled     14423
Processing    14191
Returned      14181
Name: count, dtype: int64

Top 5 categories by order volume:
main_category
Clothing                 63193
Jewellery                12430
Footwear                  6312
Home Furnishing           2563
Mobiles & Accessories     2227
Name: count, dtype: int64

Payment method split:
payment_method
UPI            38294
Credit Card    18014
Debit Card     14929
COD            11910
Net Banking     9898
EMI             6955
Name: count, dtype: int64

Big Billion Days vs Regular Day avg orders:
  Big Billion Days: 315 orders/day
  Regular days:     134 orders/day
  Spike multiplier: 2.4x

In [66]:
#  STEP 7 — Save all 5 tables as CSV
# ─────────────────────────────────────────────────────────────
dim_products.to_csv('dim_products.csv',   index=False)
dim_customers.to_csv('dim_customers.csv', index=False)
dim_sellers.to_csv('dim_sellers.csv',     index=False)
fact_orders.to_csv('fact_orders.csv',     index=False)
fact_returns.to_csv('fact_returns.csv',   index=False)
 
print("\nAll 5 CSV files saved:")
print("  dim_products.csv")
print("  dim_customers.csv")
print("  dim_sellers.csv")
print("  fact_orders.csv")
print("  fact_returns.csv")
print("\nNext step: run 01_schema_setup.sql in MySQL Workbench")

All 5 CSV files saved:
  dim_products.csv
  dim_customers.csv
  dim_sellers.csv
  fact_orders.csv
  fact_returns.csv

Next step: run 01_schema_setup.sql in MySQL Workbench

In [69]:
print("dim_products")
print(dim_products.shape)
print(dim_products.dtypes)
dim_products.head(3)

dim_products
(19922, 8)
product_id           object
product_name         object
main_category        object
brand                object
retail_price        float64
discounted_price    float64
discount_pct        float64
pop_weight          float64
dtype: object

,product_id,product_name,main_category,brand,retail_price,discounted_price,discount_pct,pop_weight
0,P00001,Alisha Solid Women's Cycling Shorts,Clothing,Alisha,999.00,379.00,62.06,0.20
1,P00002,FabHomeDecor Fabric Double Sofa Bed,Furniture,Fabhomedecor,32157.00,22646.00,29.58,0.08
2,P00003,AW Bellies,Footwear,Aw,999.00,499.00,50.05,0.10

In [67]:
# ── dim_customers ─────────────────────────────────────────
print("\n--- dim_customers ---")
print(dim_customers.shape)
print(dim_customers.dtypes)
dim_customers.head(3)

--- dim_customers ---
(10000, 6)
customer_id         object
customer_name       object
city                object
state               object
age                  int64
customer_segment    object
dtype: object

  customer_id customer_name       city      state  age customer_segment
0     C000001  Ananya Reddy     Bhopal         MP   30   Budget Shopper
1     C000002   Nikhil Iyer  Hyderabad  Telangana   29   Budget Shopper
2     C000003  Sneha Tiwari     Indore         MP   57          Regular

In [68]:
print("\n--- dim_sellers ---")
print(dim_sellers.shape)
print(dim_sellers.dtypes)
dim_sellers.head(3)

--- dim_sellers ---
(500, 5)
seller_id         object
seller_name       object
seller_city       object
seller_rating    float64
joined_year        int64
dtype: object

  seller_id          seller_name  seller_city  seller_rating  joined_year
0     S0001      ChennaiShop 139  Bhubaneswar           4.40         2022
1     S0002         DealZone 376        Delhi           4.00         2016
2     S0003  FlashSale India 179         Pune           5.00         2022

In [70]:
print("\n--- fact_orders ---")
print(fact_orders.shape)
print(fact_orders.dtypes)
fact_orders.head(3)

--- fact_orders ---
(100000, 19)
order_id               object
order_date             object
order_month             int64
order_year              int64
order_quarter          object
is_weekend              int64
is_big_billion_day      int64
is_festive_season       int64
customer_id            object
product_id             object
seller_id              object
quantity                int64
unit_price            float64
retail_price          float64
total_amount          float64
discount_pct          float64
payment_method         object
order_status           object
main_category          object
dtype: object

,order_id,order_date,order_month,order_year,order_quarter,is_weekend,is_big_billion_day,is_festive_season,customer_id,product_id,seller_id,quantity,unit_price,retail_price,total_amount,discount_pct,payment_method,order_status,main_category
0,ORD0000001,2022-10-22,10,2022,Q4,1,0,1,C003909,P16023,S0259,1,125.00,297.00,125.00,57.91,UPI,Delivered,Computers
1,ORD0000002,2022-05-26,5,2022,Q2,0,0,0,C005507,P18951,S0018,1,399.00,499.00,399.00,20.04,COD,Delivered,Jewellery
2,ORD0000003,2022-10-28,10,2022,Q4,0,0,1,C005794,P02297,S0289,1,289.00,949.00,289.00,69.55,Credit Card,Cancelled,Clothing

In [71]:
print("\n--- fact_returns ---")
print(fact_returns.shape)
print(fact_returns.dtypes)
fact_returns.head(3)

--- fact_returns ---
(14181, 9)
return_id         object
order_id          object
product_id        object
customer_id       object
main_category     object
return_date       object
return_reason     object
refund_amount    float64
return_status     object
dtype: object

,return_id,order_id,product_id,customer_id,main_category,return_date,return_reason,refund_amount,return_status
0,RET000001,ORD0000004,P12634,C009820,Jewellery,2022-07-24,Damaged in transit,1047.00,Refunded
1,RET000002,ORD0000017,P02517,C003060,Clothing,2022-11-26,Quality not as expected,259.00,Refunded
2,RET000003,ORD0000026,P01030,C002017,Jewellery,2022-10-27,Wrong item,399.00,Refunded

In [73]:
pip install sqlalchemy pymysql pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pymysql in c:\users\hp\appdata\roaming\python\python313\site-packages (1.1.3)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus
DB_USER     = 'root'
DB_PASSWORD = quote_plus('learning123@')  
DB_HOST     = '127.0.0.1'
DB_PORT     = '3306'
DB_NAME     = 'flipkart_sales'
 
engine = create_engine(
    f'mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
)

In [78]:
# Remove pop_weight column before pushing
dim_products = dim_products.drop(columns=['pop_weight'], errors='ignore')

# Verify it's gone
print("Columns in dim_products:")
print(dim_products.columns.tolist())

Columns in dim_products:
['product_id', 'product_name', 'main_category', 'brand', 'retail_price', 'discounted_price', 'discount_pct']

In [81]:
tables = [
    ('dim_products',  dim_products),
    ('dim_customers', dim_customers),
    ('dim_sellers',   dim_sellers),
    ('fact_orders',   fact_orders),
    ('fact_returns',  fact_returns),
]

for table_name, df in tables:
    df.to_sql(
        name      = table_name,
        con       = engine,
        if_exists = 'append',
        index     = False,
        chunksize = 500
    )
    print(f"  Loaded {table_name:<20} {len(df):>8,} rows ✓")

print("\nAll 5 tables loaded!")

  Loaded dim_products           19,922 rows ✓
  Loaded dim_customers          10,000 rows ✓
  Loaded dim_sellers               500 rows ✓
  Loaded fact_orders           100,000 rows ✓
  Loaded fact_returns           14,181 rows ✓

All 5 tables loaded!